// SPDX-License-Identifier: BUSL-1.1
pragma solidity ^0.8.27;

// @title Protocol Version Constants
// @notice This file is auto-generated by the Rust build system from Cargo.toml
// @dev DO NOT EDIT MANUALLY - Changes will be overwritten on next build
// @dev To update versions, modify the workspace version in the root Cargo.toml

// Protocol version following SemVer 2.0.0 (MAJOR.MINOR.PATCH)
string constant PROTOCOL_VERSION = "0.1.3";

// Minimum compatible policy factory version
string constant MIN_COMPATIBLE_POLICY_VERSION = "0.1.3";

// Minimum compatible policy data factory version
string constant MIN_COMPATIBLE_POLICY_DATA_VERSION = "0.1.3";
