// SPDX-License-Identifier: BUSL-1.1
pragma solidity ^0.8.27;

// @title Protocol Version Constants
// @notice This file is auto-generated by the Rust build system from Cargo.toml
// @dev DO NOT EDIT MANUALLY - Changes will be overwritten on next build
// @dev To update versions, modify the workspace version in the root Cargo.toml
// @dev MIN_COMPATIBLE version uses MAJOR.MINOR.0 (patch is ignored for compatibility)

// Protocol version following SemVer 2.0.0 (MAJOR.MINOR.PATCH)
string constant PROTOCOL_VERSION = "0.2.0";

// Minimum compatible factory version (MAJOR.MINOR.0)
string constant MIN_COMPATIBLE_VERSION = "0.2.0";
