// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.27;

import {INewtonProverTaskManager} from "../interfaces/INewtonProverTaskManager.sol";
import {NewtonMessage} from "../core/NewtonMessage.sol";
import {INewtonPolicyClient} from "../interfaces/INewtonPolicyClient.sol";
import {IERC165} from "@openzeppelin/contracts/interfaces/IERC165.sol";
import {PolicyValidationLib} from "./PolicyValidationLib.sol";
import {TaskManagerErrors} from "./TaskManagerErrors.sol";

/**
 * @title TaskLib
 * @dev Library for task evaluation and result processing
 */
library TaskLib {
    /* CUSTOM ERRORS */
    error TaskResponseMismatch();
    error TaskMismatch(bytes32 expected, bytes32 actual);
    error InvalidTaskId();
    error InvalidIntent();
    error InvalidIntentSignature();
    error TaskAlreadyResponded(bytes32 existingResponseHash);
    error TaskAlreadyExists(bytes32 existingTaskHash);
    error TaskResponseTooLate(
        uint32 blockNumber, uint32 taskCreatedBlock, uint32 taskResponseWindowBlock
    );
    error TaskResponseWindowNotPassed(
        uint32 blockNumber, uint32 taskCreatedBlock, uint32 taskResponseWindowBlock
    );
    error OnlyPolicyClient();
    error InvalidPolicyClient();
    error InterfaceNotSupported();
    error InvalidSourceOrDestination();
    error InvalidTaskCreatedBlock();
    error TaskCreatedBlockInFuture();
    error TaskCreatedBlockTooOld();

    /* FUNCTIONS */

    /// @notice Creates a minimal task, bounding its dynamic policy data before any policy runs.
    /// policyTaskData is generated by operators independently and validated in respondToTask.
    /// @param task The task struct with offchain estimated taskCreatedBlock
    /// @param taskCreationBufferWindow Maximum allowed age of taskCreatedBlock (in blocks)
    function createTask(
        INewtonProverTaskManager.Task calldata task,
        uint32 taskCreationBufferWindow
    ) external view returns (INewtonProverTaskManager.Task memory) {
        require(
            task.intent.from != address(0) && task.intent.to != address(0),
            InvalidSourceOrDestination()
        );

        // Validate policy client interface
        bytes4 interfaceId = type(INewtonPolicyClient).interfaceId;
        (bool success, bytes memory result) = task.policyClient
            .staticcall(abi.encodeWithSelector(IERC165.supportsInterface.selector, interfaceId));
        require(
            success && result.length == 32 && abi.decode(result, (bool)), InterfaceNotSupported()
        );

        // Validate passed taskCreatedBlock is valid for BLS signature verification
        // The block must be > 0, < current block (required by BLSSignatureChecker),
        // and within taskCreationBufferWindow blocks of current block to prevent stale state
        require(task.taskCreatedBlock > 0, InvalidTaskCreatedBlock());
        require(task.taskCreatedBlock < uint32(block.number), TaskCreatedBlockInFuture());
        require(
            uint32(block.number) - task.taskCreatedBlock <= taskCreationBufferWindow,
            TaskCreatedBlockTooOld()
        );

        PolicyValidationLib.requirePolicyDataBounds(task);

        return task;
    }

    /**
     * @dev Sanity checks the task response. Throws if any of the checks fail.
     * @param task The task
     * @param taskResponse The task response
     * @param blockNumber The block number
     * @param responseWindowBlock The response window block
     */
    function sanityCheckTaskResponse(
        INewtonProverTaskManager.Task calldata task,
        INewtonProverTaskManager.TaskResponse calldata taskResponse,
        uint32 blockNumber,
        uint32 responseWindowBlock
    ) external pure {
        require(taskResponse.taskId == task.taskId, InvalidTaskId());
        require(taskResponse.policyClient == task.policyClient, InvalidPolicyClient());
        require(taskResponse.policyId == task.policyId, TaskManagerErrors.PolicyIdMismatch());
        require(
            keccak256(abi.encode(taskResponse.intent)) == keccak256(abi.encode(task.intent)),
            InvalidIntent()
        );
        require(
            keccak256(taskResponse.intentSignature) == keccak256(task.intentSignature),
            InvalidIntentSignature()
        );
        require(
            blockNumber < task.taskCreatedBlock + responseWindowBlock,
            TaskResponseTooLate(blockNumber, task.taskCreatedBlock, responseWindowBlock)
        );
    }

    function sanityCheckAttestation(
        NewtonMessage.Attestation calldata attestation
    ) external view {
        require(
            attestation.policyId == INewtonPolicyClient(attestation.policyClient).getPolicyId(),
            TaskManagerErrors.PolicyIdMismatch()
        );
    }

    // onlyAttestationClient is used to restrict validateAttestation from only being called by the correct policy client
    function onlyAttestationClient(
        address caller,
        NewtonMessage.Attestation calldata attestation
    ) external view {
        require(caller.code.length > 0, OnlyPolicyClient());

        bytes4 interfaceId = type(INewtonPolicyClient).interfaceId;

        (bool success, bytes memory result) = caller.staticcall(
            abi.encodeWithSelector(IERC165.supportsInterface.selector, interfaceId)
        );

        require(
            success && result.length == 32 && abi.decode(result, (bool)), InterfaceNotSupported()
        );

        require(caller == attestation.policyClient, InvalidPolicyClient());
    }

    function taskHash(
        INewtonProverTaskManager.Task calldata task
    ) external pure returns (bytes32) {
        return keccak256(
            abi.encode(
                task.taskId,
                task.taskCreatedBlock,
                task.intent,
                task.intentSignature,
                task.policyClient,
                task.policyId,
                task.policyRevision,
                keccak256(abi.encode(task.policies)),
                keccak256(abi.encode(task.wasmArgs)),
                task.quorumNumbers,
                task.quorumThresholdPercentage,
                task.initializationTimestamp
            )
        );
    }

    /**
     * @notice Computes the consensus digest for BLS signature aggregation.
     * @param taskResponse The task response to compute the consensus digest for
     * @return The keccak256 hash of the task response
     */
    function computeConsensusDigest(
        INewtonProverTaskManager.TaskResponse memory taskResponse
    ) internal pure returns (bytes32) {
        return keccak256(abi.encode(taskResponse));
    }
}
