// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.27;

import "@eigenlayer-middleware/src/libraries/BN254.sol";
import {NewtonMessage} from "../core/NewtonMessage.sol";
import {INewtonPolicy} from "./INewtonPolicy.sol";

interface INewtonProverTaskManager {
    // EVENTS
    event NewTaskCreated(bytes32 indexed taskId, Task task, INewtonPolicy.PolicyState state);

    event TaskResponded(TaskResponse taskResponse, ResponseCertificate responseCertificate);

    event TaskChallengedSuccessfully(bytes32 indexed taskId, address indexed challenger);

    event TaskChallengedUnsuccessfully(bytes32 indexed taskId, address indexed challenger);

    event AttestationSpent(bytes32 indexed taskId, NewtonMessage.Attestation attestation);

    event DirectTaskResponded(bytes32 indexed taskId, Task task, TaskResponse taskResponse);

    event AggregatorUpdated(address indexed previousAggregator, address indexed newAggregator);

    event TaskResponseHandlerUpdated(address indexed newHandler);

    // STRUCTS
    // Task struct represents the minimal on-chain task data.
    // policyTaskData and policyConfig are moved to TaskResponse - operators generate these independently.
    // Task is completed when quorumNumbers are signed by at least quorumThresholdPercentage of operators.
    struct Task {
        // the unique identifier for the task
        bytes32 taskId;
        // policy client address
        address policyClient;
        // the block number when the task was created
        uint32 taskCreatedBlock;
        // the quorum threshold percentage of the task
        uint32 quorumThresholdPercentage;
        // the intent of the task
        NewtonMessage.Intent intent;
        // the signature of the intent by the intent creator
        bytes intentSignature;
        // task request WASM args - operators use this to generate policyTaskData
        bytes wasmArgs;
        // the quorum numbers of the task
        bytes quorumNumbers;
        // timestamp marking the offchain ingestion of the task
        uint256 initializationTimestamp;
    }

    // Task response is hashed and signed by operators.
    // Operators generate policyTaskData independently using wasmArgs from Task.
    // Aggregator validates consistency of policyTaskData across operator responses.
    struct TaskResponse {
        // Can be obtained by the operator from the event NewTaskCreated.
        bytes32 taskId;
        // policy client address
        address policyClient;
        // policy id of the task (derived from policyTaskData)
        bytes32 policyId;
        // the policy address of the task (from policyTaskData)
        address policyAddress;
        // the intent of the task
        NewtonMessage.Intent intent;
        // the signature of the intent by the intent creator
        bytes intentSignature;
        // Policy evaluation result.
        bytes evaluationResult;
        // the policy task data - generated by operators, validated by aggregator
        NewtonMessage.PolicyTaskData policyTaskData;
        // policy configuration - fetched by operators from chain
        INewtonPolicy.PolicyConfig policyConfig;
        // timestamp marking the offchain ingestion of the task
        uint256 initializationTimestamp;
    }

    // Certificate is filled by the protocol contract for each taskResponse signed by operators.
    // This Certificate is used by policy clients to attest the validity of policy evaluation result
    // during intent execution.
    // This certificate is also used by the challenger, who monitors and if invalid, raises challenge
    // with zero-knowledge proof of the policy evaluation result discrepancy.
    // NOTE: this can be used as an attestation for not just single chain but multi-chain attestation.
    struct ResponseCertificate {
        // the block number when the response certificate is created
        uint32 referenceBlock;
        // the block number when the task response expires
        uint32 responseExpireBlock;
        // the hash of the non-signers
        bytes32 hashOfNonSigners;
        // encoded signature data (NonSignerStakesAndSignature for source chains, BN254Certificate for destination)
        bytes signatureData;
    }

    // Challenge data is submitted by the challenger.
    // Contains the proof data and verification key for onchain verification of the policy evaluation result.
    // TODO: add support for risc0 zk proofs, and other proof types.
    struct ChallengeData {
        // Can be obtained by the operator from the event NewTaskCreated.
        bytes32 taskId;
        // sp1 zk proof to attest the policy evaluation result of the challenger
        bytes proof;
        // The committed proof output to verify against the task response data.
        bytes data;
    }

    // State getter functions
    // See TaskManagerStorage.sol for documentation
    function isDestinationChain() external view returns (bool);
    function nonce() external view returns (uint32);
    function serviceManager() external view returns (address);
    function certificateVerifier() external view returns (address);
    function operatorRegistry() external view returns (address);
    function taskResponseHandler() external view returns (address);
    function allTaskHashes(
        bytes32
    ) external view returns (bytes32);
    function allTaskResponses(
        bytes32
    ) external view returns (bytes32);
    function challengeVerifier() external view returns (address);
    function attestationValidator() external view returns (address);
    function taskResponseWindowBlock() external view returns (uint32);
    function epochBlocks() external view returns (uint32);
    function taskCreationBufferWindow() external view returns (uint32);
    function minCompatiblePolicyVersion() external view returns (string memory);
    function minCompatiblePolicyDataVersion() external view returns (string memory);

    // FUNCTIONS
    // NOTE: this function creates new task.
    // Task now contains minimal data - operators generate policyTaskData independently.
    function createNewTask(
        Task calldata task
    ) external;

    // NOTE: this function responds to existing tasks.
    function respondToTask(
        Task calldata task,
        TaskResponse calldata taskResponse,
        bytes calldata signatureData,
        bytes calldata attestationData
    ) external;

    // NOTE: this function raises challenge to existing tasks.
    function raiseAndResolveChallenge(
        Task calldata task,
        TaskResponse calldata taskResponse,
        ResponseCertificate calldata responseCertificate,
        ChallengeData calldata challenge,
        BN254.G1Point[] calldata pubkeysOfNonSigningOperators
    ) external;

    /// @notice Relay a cross-chain challenge from a destination chain to trigger slashing on source
    /// @dev Re-executes ZK proof on source chain. Does not require the task to exist locally.
    /// @param destChainId The destination chain where the task was created
    /// @param task The original task from the destination chain
    /// @param taskResponse The task response being challenged
    /// @param challenge ZK proof data proving the response was incorrect
    /// @param pubkeysOfNonSigningOperators BLS G1 pubkeys of non-signing operators
    function slashForCrossChainChallenge(
        uint256 destChainId,
        Task calldata task,
        TaskResponse calldata taskResponse,
        ChallengeData calldata challenge,
        bytes calldata signatureData,
        BN254.G1Point[] memory pubkeysOfNonSigningOperators
    ) external;

    // NOTE: this function authorizes existing task responses.
    function validateAttestation(
        NewtonMessage.Attestation calldata attestation
    ) external returns (bool);

    // NOTE: this function validates attestation directly by verifying signatures
    // without waiting for respondToTask to be called.
    // signatureData is ABI-encoded NonSignerStakesAndSignature (source) or BN254Certificate (destination)
    function validateAttestationDirect(
        Task calldata task,
        TaskResponse calldata taskResponse,
        bytes calldata signatureData
    ) external returns (bool);

    // NOTE: this function challenges directly verified attestations when respondToTask
    // was never called after the taskResponseWindow has passed.
    function challengeDirectlyVerifiedAttestation(
        Task calldata task,
        TaskResponse calldata taskResponse,
        bytes calldata signatureData
    ) external;

    /// @notice Invalidate a direct-path attestation whose stored hashes diverge from
    /// the canonical regular-path hashes. Marks the task as challenged and invalidates
    /// the direct-path attestation so downstream consumers stop trusting its hashes.
    /// Never slashes — hash divergence alone is not proof of operator misbehavior.
    /// See `ChallengeVerifier.challengeDirectlyVerifiedMismatch` for rationale.
    function challengeDirectlyVerifiedMismatch(
        Task calldata task,
        TaskResponse calldata taskResponse
    ) external;

    /// @notice Returns the task-identity hash recorded when the task was created.
    function taskHash(
        bytes32 taskId
    ) external view returns (bytes32);

    /// @notice Returns `keccak256(abi.encode(taskResponse, responseCertificate))` for the
    /// regular response path. Includes the response certificate, so this is NOT comparable
    /// to direct-path hashes. Use `normalizedTaskResponseHash` for direct-vs-regular checks.
    function taskResponseHash(
        bytes32 taskId
    ) external view returns (bytes32);

    /// @notice Returns `keccak256(abi.encode(taskResponse))` — the response-only hash without
    /// the response certificate, synced with the direct-path encoding in `AttestationValidator`.
    /// Used as the canonical side of mismatch checks in `ChallengeVerifier`.
    function normalizedTaskResponseHash(
        bytes32 taskId
    ) external view returns (bytes32);
}
